### ISSUE TITLE
Hacktoberfest welcome

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart-store#150]
Main welcome: bitcartcc/bitcart#133

Issue list:
- [x] Fix favicon barely visible in darkmode (#146)
- [x] Add prettier to the project (#152)

**Comment by SakshamSingh-v2** [comment]
I would like to work on this issue!

**Comment by MrNaif2018** [comment]
Hi! Thank you! We've now got a favicon prepared, so all that is left is to use this favicon.ico and test if it works:
https://github.com/bitcartcc/bitcart-media/blob/master/favicon.ico

**Comment by MrNaif2018** [comment]
Thanks to everyone who has contributed to BitcartCC this hacktoberfest!
