### ISSUE TITLE
Hacktoberfest welcome

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart-store#317]
Main welcome: bitcartcc/bitcart#243

Issue list (more to be added):

- [x] #316 
- [ ] #318 
- [ ] #319 
- [ ] #320
- [ ] #322 
- [ ] #323 
- [x] #324

**Comment by beatrizsmerino** [comment]
ok I just saw the list, I'm going to get to work on this [https://github.com/bitcartcc/bitcart-store/issues/319](https://github.com/bitcartcc/bitcart-store/issues/319)

**Comment by MrNaif2018** [comment]
Thanks to everyone who has contributed to BitcartCC this hacktoberfest! You are welcome to contribute any time of the year of course!
