### ISSUE TITLE
Add pre-commit

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart-store#320]
Same as in bitcartcc/bitcart-admin#122, but for bitcartcc store. If possible, all js repos should follow the same pre-commit config

**Comment by MaximeKoitsalu** [comment]
I can check this one out as well. In addition to `yarn lint-staged` I can add so prettier runs on sass files too. Anything else you want in the precommits?

**Comment by MrNaif2018** [comment]
Check out the updated bitcart-admin description.
The main issue is to somehow make pre-commit work with our eslint, prettier plugins without pinning them to some exact versions in pre-commit config file, but instead in package.json only. Maybe it would be made a local hook (which requires user to have node_modules existing and will probably assume yarn)

https://github.com/bitcartcc/bitcart/blob/master/.pre-commit-config.yaml
You can use this as base, remove python ones and fix js ones to work with linter plugins
So that prettier will run by it's own hook on all files, and regular eslint linting by yarn lint

Also actually we've got lint staged and husky already. lint-staged should be removed and maybe husky if you figure out how to run linting from pre-commit

I suggest checking out https://pre-commit.com/hooks.html and seeing if there is something useful we could apply too

**Comment by MaximeKoitsalu** [comment]
I'm unfamiliar with the `pre-commit` library. I will read a bit more about it and get back to you! Thanks for the clarification.

**Comment by MrNaif2018** [comment]
Hi @MaximeKoitsalu! Do you need some help in setting it up? Any questions so far?
