### ISSUE TITLE
Show cart panel on the right

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart-store#324]
Currently to visit the cart, user has to press cart button. It is suboptimal
If cart is not empty, on the right side of the screen cart panel should be displayed, showing selected products, allowing to edit quantity and with link to go to checkout. Existing components for cart may be re-used (maybe with slight modifications)

**Comment by Xaconi** [comment]
hey @MrNaif2018 can i work on this one?

**Comment by MrNaif2018** [comment]
Of course!

**Comment by Xaconi** [comment]
I think I need some environment variables on a .env file? Even with the project built and running on dev (`npm run dev`) the app returns me this error:

![image](https://user-images.githubusercontent.com/1944438/135750401-4df5d366-6ea1-464f-806f-2fad04549f6f.png)

**Comment by MrNaif2018** [comment]
Sorry for the current suboptimal experience, see #318
See this comment for how to set up the merchants api (two ways):
https://github.com/bitcartcc/bitcart-store/issues/316#issuecomment-932450528
